name: Bad CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip

      - name: Install requirements
        run: pip3 install -r requirements.txt

      - name: Run tests
        run: python3 test.py

      - name: Save logs
        run: |
          mkdir artifacts
          cp *.log artifacts/
